# Site settings
title: Garden's Blog
SEOTitle: 东方甲的博客 | Garden's Blog
header-img: img/home-bg.jpg
email: cjdxjtu@qq.com
description: "关于程序与设计、云计算与摄影 | Garden，Web & photography Lover，Software Engineer， | 这里是 Garden 的个人博客，与你一起发现更大的世界。"
keyword: "Garden, GardenChen, 秦漳, 西安交通大学, Garden的博客, Garden's Blog, 博客, 个人网站, 互联网, Web, Golang, 后端, 云原生, Java, Python"
url: "https://blog.cjd2022.xyz"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: u/5836272908
zhihu_username: gardenchan
github_username: GardenChan
# twitter_username: 
#facebook_username:  
# linkedin_username:  firstname-lastname-idxxxx
# wechat_username: gardenchan
douyin_username: MS4wLjABAAAAboEE0Qj6kR5ZCGZbarlc91POcYU5UColjX9cJIc9l31EI4LfCVsnUYyTu6CIu3xu
csdn_username: weixin_44870909



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: blog-wfeszeili4

# Netease settings
netease_comment: true



# Analytics settings
# Baidu Analytics 
ba_track_id: [b77fb9e5c397c998c29c7859689e8166]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Garden-东方甲<br>本硕毕业于西安交通大学<br>软件开发工程师<br>深耕云计算行业"
sidebar-avatar: /img/sidebar-avatar.jpg # https://github.com/GardenChan.png # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "MySQL",
        href: "https://www.mysql.com/"
    },{
        title: "K8s",
        href: "https://kubernetes.io/"
    },{
        title: "gRPC",
        href: "https://www.grpc.io/"
    },{
        title: "Spring",
        href: "https://spring.io/"
    },{
        title: "WebAssembly",
        href: "https://webassembly.org/"
    },{
        title: "Golang",
        href: "https://golang.google.cn/"
    },{
        title: "Docker",
        href: "https://www.docker.com/"
    },{
        title: "语雀",
        href: "https://www.yuque.com/"
    }
]
